name: My First Workflow

on: [push,fork]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              
            - name: Welcome message
              run: echo "My first Github Actions Job v6" 
            
            - name: Where am I
              run: pwd

            - name: List files
              run: ls

            - name: Read file
              run: cat README.md